use std::env;
use std::fs::{self, OpenOptions};
use std::io::{self, Write};
use std::path::{Component, Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::atomic::{AtomicU64, Ordering};

use anyhow::{Context, Result};
use thiserror::Error;

use super::{BackendKind, build_backend_process_spec};
use crate::terminal::ProcessSpec;
use crate::workspace::Workspace;

const PROFILE_VERSION: &str = "managed-v1";
const APP_NAME: &str = "ami-code-managed-v1";
const OVERLAY_ENV: &str = "AMI_CODE_NVIM_USER_OVERLAY";
const INIT_LUA: &str = r#"-- Generated by ami-code. Do not edit.
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.g.loaded_netrwSettings = 1
vim.g.loaded_netrwFileHandlers = 1
vim.o.loadplugins = false
local overlay = vim.env.AMI_CODE_NVIM_USER_OVERLAY
if overlay and overlay ~= "" then
  local stat = (vim.uv or vim.loop).fs_stat(overlay)
  if not stat or stat.type ~= "file" then
    error("AMI_CODE_NVIM_USER_OVERLAY is not a readable file: " .. overlay)
  end
  dofile(overlay)
end
"#;
static TEMP_SEQUENCE: AtomicU64 = AtomicU64::new(0);

#[allow(dead_code)]
#[derive(Debug, Clone, Copy, Default)]
pub struct NvimBackend;

/// Materialized, versioned configuration for the isolated managed Nvim profile.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ManagedNvimProfile {
    init_path: PathBuf,
}

impl ManagedNvimProfile {
    pub fn from_environment() -> Result<Self> {
        Self::materialize(state_root_from_environment()?)
    }

    pub fn materialize(state_root: impl AsRef<Path>) -> Result<Self> {
        let directory = state_root.as_ref().join("nvim").join(PROFILE_VERSION);
        create_private_dir_all(&directory).with_context(|| {
            format!(
                "failed to create managed Nvim profile at {}",
                directory.display()
            )
        })?;
        let init_path = directory.join("init.lua");
        atomic_replace(&init_path, INIT_LUA.as_bytes()).with_context(|| {
            format!(
                "failed to materialize managed Nvim init at {}",
                init_path.display()
            )
        })?;
        Ok(Self { init_path })
    }

    pub fn init_path(&self) -> &Path {
        &self.init_path
    }

    pub fn generation(&self, workspace: &Workspace) -> Result<ManagedNvimGeneration> {
        ManagedNvimGeneration::new(self, workspace)
    }
}

/// One Nvim process generation and its unique, short-lived listen endpoint.
#[derive(Debug)]
pub struct ManagedNvimGeneration {
    spec: ProcessSpec,
    endpoint: PathBuf,
    _runtime_dir: tempfile::TempDir,
}

#[allow(dead_code)]
impl ManagedNvimGeneration {
    fn new(profile: &ManagedNvimProfile, workspace: &Workspace) -> Result<Self> {
        let runtime_dir = tempfile::Builder::new()
            .prefix("ami-nv-")
            .tempdir()
            .context("failed to create private Nvim runtime directory")?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(runtime_dir.path(), fs::Permissions::from_mode(0o700))
                .context("failed to secure private Nvim runtime directory")?;
        }
        let endpoint = runtime_dir.path().join("nvim.sock");
        let init_path = profile
            .init_path()
            .to_str()
            .context("managed Nvim init path is not valid UTF-8")?;
        let endpoint_arg = endpoint
            .to_str()
            .context("managed Nvim endpoint path is not valid UTF-8")?;
        let mut spec = build_backend_process_spec("nvim", "nvim", workspace);
        spec.args = vec![
            "-u".into(),
            init_path.to_owned(),
            "--noplugin".into(),
            "-i".into(),
            "NONE".into(),
            "--listen".into(),
            endpoint_arg.to_owned(),
        ];
        spec.env.insert("NVIM_APPNAME".into(), APP_NAME.into());
        // Overlay inheritance is deliberately opt-in. If present, normalize it
        // to an absolute path; otherwise the managed init has no user hook.
        if let Some(overlay) = env::var_os(OVERLAY_ENV) {
            let overlay = absolute_path(Path::new(&overlay))?;
            let overlay = overlay
                .to_str()
                .context("managed Nvim overlay path is not valid UTF-8")?;
            spec.env.insert(OVERLAY_ENV.into(), overlay.to_owned());
        }
        Ok(Self {
            spec,
            endpoint,
            _runtime_dir: runtime_dir,
        })
    }

    pub fn process_spec(&self) -> &ProcessSpec {
        &self.spec
    }

    pub fn endpoint(&self) -> &Path {
        &self.endpoint
    }

    pub fn controller(&self, workspace: &Workspace) -> NvimController {
        NvimController::new(workspace.root().to_path_buf(), Some(self.endpoint.clone()))
    }

    pub fn cleanup(&self) -> Result<()> {
        remove_endpoint(&self.endpoint)
    }
}

impl Drop for ManagedNvimGeneration {
    fn drop(&mut self) {
        let _ = remove_endpoint(&self.endpoint);
    }
}

#[derive(Debug, Clone)]
pub struct NvimController {
    workspace_root: PathBuf,
    endpoint: Option<PathBuf>,
}

#[allow(dead_code)]
#[derive(Debug, Error)]
pub enum NvimRemoteError {
    #[error("Nvim has no active endpoint")]
    NoEndpoint,
    #[error("Nvim endpoint is not ready: {0}")]
    NotReady(PathBuf),
    #[error("path is outside the workspace: {0}")]
    OutsideWorkspace(PathBuf),
    #[error("path is not valid UTF-8 and cannot be passed to Nvim: {0}")]
    NonUtf8Path(PathBuf),
    #[error("failed to resolve remote-open path: {0}")]
    InvalidPath(#[source] anyhow::Error),
    #[error("path is not an existing regular file: {0}")]
    NotRegularFile(PathBuf),
    #[error("failed to execute Nvim remote command: {0}")]
    Command(#[source] io::Error),
    #[error("Nvim remote command failed with {0}")]
    RemoteFailure(std::process::ExitStatus),
}

#[allow(dead_code)]
impl NvimController {
    pub fn new(workspace_root: PathBuf, endpoint: Option<PathBuf>) -> Self {
        Self {
            workspace_root,
            endpoint,
        }
    }

    pub fn endpoint(&self) -> Option<&Path> {
        self.endpoint.as_deref()
    }

    pub fn replace_endpoint(&mut self, endpoint: Option<PathBuf>) {
        self.endpoint = endpoint;
    }

    pub fn remote_open_spec(&self, path: impl AsRef<Path>) -> Result<ProcessSpec, NvimRemoteError> {
        let absolute = workspace_safe_path(&self.workspace_root, path.as_ref())?;
        self.remote_open_spec_for_absolute(absolute)
    }

    /// Builds a remote-open command only for an existing regular file whose
    /// canonical target is inside the canonical workspace root. Symlink files
    /// are accepted; escaping symlinks and every non-regular file are rejected.
    pub fn existing_file_open_spec(
        &self,
        path: impl AsRef<Path>,
    ) -> Result<ProcessSpec, NvimRemoteError> {
        let absolute = workspace_existing_regular_file(&self.workspace_root, path.as_ref())?;
        self.remote_open_spec_for_absolute(absolute)
    }

    fn remote_open_spec_for_absolute(
        &self,
        absolute: PathBuf,
    ) -> Result<ProcessSpec, NvimRemoteError> {
        let endpoint = self.endpoint.clone().ok_or(NvimRemoteError::NoEndpoint)?;
        if !endpoint.exists() {
            return Err(NvimRemoteError::NotReady(endpoint));
        }
        let endpoint_arg = endpoint
            .to_str()
            .ok_or_else(|| NvimRemoteError::NonUtf8Path(endpoint.clone()))?;
        let absolute_arg = absolute
            .to_str()
            .ok_or_else(|| NvimRemoteError::NonUtf8Path(absolute.clone()))?;
        let mut spec = ProcessSpec::new("nvim").display_name("nvim remote");
        spec.args = vec![
            "--server".into(),
            endpoint_arg.to_owned(),
            "--remote-tab-silent".into(),
            absolute_arg.to_owned(),
        ];
        spec.cwd = Some(self.workspace_root.clone());
        spec.env.insert("NVIM_APPNAME".into(), APP_NAME.into());
        Ok(spec)
    }

    /// Executes a one-shot argv-based remote open. No path is interpreted by a shell.
    pub fn open(&self, path: impl AsRef<Path>) -> Result<(), NvimRemoteError> {
        self.execute(self.remote_open_spec(path)?)
    }

    /// Executes the strict existing-regular-file variant used by Sidebar.
    pub fn open_existing_file(&self, path: impl AsRef<Path>) -> Result<(), NvimRemoteError> {
        self.execute(self.existing_file_open_spec(path)?)
    }

    fn execute(&self, spec: ProcessSpec) -> Result<(), NvimRemoteError> {
        execute_remote_spec(spec)
    }
}

fn execute_remote_spec(spec: ProcessSpec) -> Result<(), NvimRemoteError> {
    let cwd = spec.cwd.as_ref().ok_or_else(|| {
        NvimRemoteError::InvalidPath(anyhow::anyhow!("Nvim controller has no workspace cwd"))
    })?;
    let mut command = Command::new(&spec.program);
    command
        .args(&spec.args)
        .current_dir(cwd)
        // A one-shot `nvim --server --remote` detects inherited raw TTYs and
        // enters/leaves the alternate screen, corrupting the parent ratatui
        // display. It does not need interactive streams.
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null());
    for (key, value) in &spec.env {
        command.env(key, value);
    }
    let status = command.status().map_err(NvimRemoteError::Command)?;
    if !status.success() {
        return Err(NvimRemoteError::RemoteFailure(status));
    }
    Ok(())
}

#[allow(dead_code)]
impl NvimBackend {
    pub fn kind(self) -> BackendKind {
        BackendKind::Editor
    }

    pub fn display_name(self) -> &'static str {
        "nvim"
    }
}

fn state_root_from_environment() -> Result<PathBuf> {
    if let Some(path) = env::var_os("AMI_CODE_STATE_DIR") {
        return Ok(PathBuf::from(path));
    }
    if let Some(path) = env::var_os("XDG_STATE_HOME") {
        return Ok(PathBuf::from(path).join("ami-code"));
    }
    let home = env::var_os("HOME")
        .map(PathBuf::from)
        .context("no state directory: set AMI_CODE_STATE_DIR, XDG_STATE_HOME, or HOME")?;
    #[cfg(target_os = "macos")]
    return Ok(home.join("Library/Application Support/ami-code"));
    #[cfg(not(target_os = "macos"))]
    Ok(home.join(".local/state/ami-code"))
}

fn remove_endpoint(path: &Path) -> Result<()> {
    match fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(error) => {
            Err(error).with_context(|| format!("failed to remove Nvim endpoint {}", path.display()))
        }
    }
}

fn workspace_safe_path(root: &Path, requested: &Path) -> Result<PathBuf, NvimRemoteError> {
    let candidate = normalize_absolute(if requested.is_absolute() {
        requested.to_path_buf()
    } else {
        root.join(requested)
    });
    let mut missing = Vec::new();
    let mut existing = candidate.as_path();
    while !existing.exists() {
        let name = existing.file_name().ok_or_else(|| {
            NvimRemoteError::InvalidPath(anyhow::anyhow!("path has no existing ancestor"))
        })?;
        missing.push(name.to_os_string());
        existing = existing
            .parent()
            .ok_or_else(|| NvimRemoteError::InvalidPath(anyhow::anyhow!("path has no parent")))?;
    }
    let root = root
        .canonicalize()
        .map_err(|error| NvimRemoteError::InvalidPath(error.into()))?;
    let mut resolved = existing
        .canonicalize()
        .map_err(|error| NvimRemoteError::InvalidPath(error.into()))?;
    if !resolved.starts_with(&root) {
        return Err(NvimRemoteError::OutsideWorkspace(candidate));
    }
    for component in missing.into_iter().rev() {
        resolved.push(component);
    }
    Ok(resolved)
}

fn workspace_existing_regular_file(
    root: &Path,
    requested: &Path,
) -> Result<PathBuf, NvimRemoteError> {
    let candidate = if requested.is_absolute() {
        requested.to_path_buf()
    } else {
        root.join(requested)
    };
    let root = root
        .canonicalize()
        .map_err(|error| NvimRemoteError::InvalidPath(error.into()))?;
    let resolved = candidate
        .canonicalize()
        .map_err(|error| NvimRemoteError::InvalidPath(error.into()))?;
    if !resolved.starts_with(&root) {
        return Err(NvimRemoteError::OutsideWorkspace(candidate));
    }
    let metadata =
        fs::metadata(&resolved).map_err(|error| NvimRemoteError::InvalidPath(error.into()))?;
    if !metadata.is_file() {
        return Err(NvimRemoteError::NotRegularFile(candidate));
    }
    Ok(resolved)
}

fn normalize_absolute(path: PathBuf) -> PathBuf {
    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            Component::Prefix(prefix) => normalized.push(prefix.as_os_str()),
            Component::RootDir => normalized.push(component.as_os_str()),
            Component::CurDir => {}
            Component::ParentDir => {
                normalized.pop();
            }
            Component::Normal(value) => normalized.push(value),
        }
    }
    normalized
}

fn absolute_path(path: &Path) -> Result<PathBuf> {
    if path.is_absolute() {
        Ok(path.to_path_buf())
    } else {
        Ok(env::current_dir()?.join(path))
    }
}

fn create_private_dir_all(path: &Path) -> Result<()> {
    fs::create_dir_all(path)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(path, fs::Permissions::from_mode(0o700))?;
    }
    Ok(())
}

fn atomic_replace(path: &Path, contents: &[u8]) -> Result<()> {
    let parent = path.parent().context("managed asset has no parent")?;
    let temporary = parent.join(format!(
        ".init.lua.tmp-{}-{}",
        std::process::id(),
        TEMP_SEQUENCE.fetch_add(1, Ordering::Relaxed)
    ));
    let mut options = OpenOptions::new();
    options.write(true).create_new(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.mode(0o600);
    }
    let result = (|| -> Result<()> {
        let mut file = options.open(&temporary)?;
        file.write_all(contents)?;
        file.sync_all()?;
        fs::rename(&temporary, path)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(path, fs::Permissions::from_mode(0o600))?;
        }
        Ok(())
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};
    use std::time::{SystemTime, UNIX_EPOCH};

    static NEXT_TEMP_ID: AtomicU64 = AtomicU64::new(1);

    fn temp(label: &str) -> PathBuf {
        env::temp_dir().join(format!(
            "ami-code-{label}-{}-{}-{}",
            std::process::id(),
            SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos(),
            NEXT_TEMP_ID.fetch_add(1, Ordering::Relaxed)
        ))
    }

    #[test]
    fn materialization_is_versioned_atomic_and_private() {
        let root = temp("profile");
        let profile = ManagedNvimProfile::materialize(&root).unwrap();
        assert!(profile.init_path().ends_with("nvim/managed-v1/init.lua"));
        assert_eq!(fs::read_to_string(profile.init_path()).unwrap(), INIT_LUA);
        ManagedNvimProfile::materialize(&root).unwrap();
        assert!(
            !fs::read_dir(profile.init_path().parent().unwrap())
                .unwrap()
                .any(|entry| entry
                    .unwrap()
                    .file_name()
                    .to_string_lossy()
                    .contains(".tmp-"))
        );
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(
                fs::metadata(profile.init_path())
                    .unwrap()
                    .permissions()
                    .mode()
                    & 0o777,
                0o600
            );
        }
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn generation_spec_is_isolated_and_unique() {
        let root = temp("workspace");
        fs::create_dir_all(&root).unwrap();
        let workspace = Workspace::discover(&root).unwrap();
        let profile = ManagedNvimProfile::materialize(temp("state")).unwrap();
        let first = profile.generation(&workspace).unwrap();
        let second = profile.generation(&workspace).unwrap();
        assert_ne!(first.endpoint(), second.endpoint());
        assert_eq!(first.process_spec().cwd.as_deref(), Some(workspace.root()));
        assert_eq!(
            first
                .process_spec()
                .env
                .get("NVIM_APPNAME")
                .map(String::as_str),
            Some(APP_NAME)
        );
        assert_eq!(
            &first.process_spec().args[0..5],
            &[
                "-u",
                profile.init_path().to_str().unwrap(),
                "--noplugin",
                "-i",
                "NONE"
            ]
        );
        assert!(first.endpoint().as_os_str().len() < 90);
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(
                fs::metadata(first.endpoint().parent().unwrap())
                    .unwrap()
                    .permissions()
                    .mode()
                    & 0o777,
                0o700
            );
        }
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn endpoint_cleanup_removes_stale_and_shutdown_files() {
        let root = temp("workspace");
        fs::create_dir_all(&root).unwrap();
        let workspace = Workspace::discover(&root).unwrap();
        let profile = ManagedNvimProfile::materialize(temp("state")).unwrap();
        let generation = profile.generation(&workspace).unwrap();
        fs::write(generation.endpoint(), b"stale").unwrap();
        generation.cleanup().unwrap();
        assert!(!generation.endpoint().exists());
        fs::write(generation.endpoint(), b"stale").unwrap();
        let endpoint = generation.endpoint().to_path_buf();
        let runtime_dir = endpoint.parent().unwrap().to_path_buf();
        drop(generation);
        assert!(!endpoint.exists());
        assert!(!runtime_dir.exists());
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn remote_open_preserves_path_as_one_argv_value() {
        let root = temp("workspace");
        fs::create_dir_all(&root).unwrap();
        let workspace = Workspace::discover(&root).unwrap();
        let endpoint = root.join("server.sock");
        fs::write(&endpoint, b"").unwrap();
        let controller = NvimController::new(workspace.root().to_path_buf(), Some(endpoint));
        for path in [
            "with spaces.txt",
            "unicodé-文件.rs",
            "-leading-dash",
            "missing/leaf.txt",
        ] {
            if path.contains('/') {
                fs::create_dir_all(root.join("missing")).unwrap();
            }
            let spec = controller.remote_open_spec(path).unwrap();
            assert_eq!(spec.args.len(), 4);
            assert_eq!(Path::new(&spec.args[3]), workspace.root().join(path));
        }
        assert!(matches!(
            controller.remote_open_spec("../escape"),
            Err(NvimRemoteError::OutsideWorkspace(_))
        ));
        assert!(matches!(
            controller.remote_open_spec("missing/../../escape"),
            Err(NvimRemoteError::OutsideWorkspace(_))
        ));
        fs::remove_dir_all(root).unwrap();
    }

    #[cfg(unix)]
    #[test]
    fn remote_open_rejects_non_utf8_paths_without_lossy_rewrite() {
        use std::os::unix::ffi::OsStringExt;

        let root = temp("workspace");
        fs::create_dir_all(&root).unwrap();
        let workspace = Workspace::discover(&root).unwrap();
        let endpoint = root.join("server.sock");
        fs::write(&endpoint, b"").unwrap();
        let controller = NvimController::new(workspace.root().to_path_buf(), Some(endpoint));
        let requested = PathBuf::from(std::ffi::OsString::from_vec(vec![b'f', 0xff]));
        assert!(matches!(
            controller.remote_open_spec(requested),
            Err(NvimRemoteError::NonUtf8Path(_))
        ));
        fs::remove_dir_all(root).unwrap();
    }

    #[cfg(unix)]
    #[test]
    fn remote_command_does_not_inherit_parent_tty_streams() {
        let root = temp("detached-remote");
        fs::create_dir_all(&root).unwrap();
        let mut spec = ProcessSpec::new("/bin/sh");
        spec.args = vec!["-c".into(), "[ ! -t 0 ] && [ ! -t 1 ] && [ ! -t 2 ]".into()];
        spec.cwd = Some(root.clone());
        execute_remote_spec(spec).unwrap();
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn strict_file_open_accepts_nested_files_and_rejects_missing_and_directories() {
        let root = temp("strict-workspace");
        fs::create_dir_all(root.join("nested/dir")).unwrap();
        fs::write(root.join("nested/file.rs"), b"").unwrap();
        fs::write(root.join("-with spaces ü.rs"), b"").unwrap();
        let endpoint = root.join("server.sock");
        fs::write(&endpoint, b"").unwrap();
        let controller = NvimController::new(root.clone(), Some(endpoint));

        let spec = controller
            .existing_file_open_spec("nested/file.rs")
            .unwrap();
        assert_eq!(
            Path::new(&spec.args[3]),
            root.join("nested/file.rs").canonicalize().unwrap()
        );
        let special = controller
            .existing_file_open_spec("-with spaces ü.rs")
            .unwrap();
        assert_eq!(special.args.len(), 4);
        assert_eq!(
            Path::new(&special.args[3]),
            root.join("-with spaces ü.rs").canonicalize().unwrap()
        );
        assert!(matches!(
            controller.existing_file_open_spec("missing"),
            Err(NvimRemoteError::InvalidPath(_))
        ));
        assert!(matches!(
            controller.existing_file_open_spec("nested/dir"),
            Err(NvimRemoteError::NotRegularFile(_))
        ));
        fs::remove_dir_all(root).unwrap();
    }

    #[cfg(unix)]
    #[test]
    fn strict_file_open_accepts_safe_symlink_and_rejects_escape_and_fifo() {
        use std::os::unix::fs::symlink;

        let root = temp("strict-links");
        let outside = temp("strict-outside");
        fs::create_dir_all(&root).unwrap();
        fs::create_dir_all(&outside).unwrap();
        fs::write(root.join("target"), b"").unwrap();
        fs::write(outside.join("outside"), b"").unwrap();
        symlink(root.join("target"), root.join("safe-link")).unwrap();
        symlink(outside.join("outside"), root.join("escape-link")).unwrap();
        let fifo = root.join("fifo");
        assert!(
            Command::new("mkfifo")
                .arg(&fifo)
                .status()
                .unwrap()
                .success()
        );
        let endpoint = root.join("server.sock");
        fs::write(&endpoint, b"").unwrap();
        let controller = NvimController::new(root.clone(), Some(endpoint));

        let spec = controller.existing_file_open_spec("safe-link").unwrap();
        assert_eq!(
            Path::new(&spec.args[3]),
            root.join("target").canonicalize().unwrap()
        );
        assert!(matches!(
            controller.existing_file_open_spec("escape-link"),
            Err(NvimRemoteError::OutsideWorkspace(_))
        ));
        assert!(matches!(
            controller.existing_file_open_spec("fifo"),
            Err(NvimRemoteError::NotRegularFile(_))
        ));
        fs::remove_dir_all(root).unwrap();
        fs::remove_dir_all(outside).unwrap();
    }

    #[test]
    fn readiness_errors_are_distinct() {
        let root = temp("workspace");
        fs::create_dir_all(&root).unwrap();
        let none = NvimController::new(root.clone(), None);
        assert!(matches!(
            none.remote_open_spec("x"),
            Err(NvimRemoteError::NoEndpoint)
        ));
        let absent = NvimController::new(root.clone(), Some(root.join("absent.sock")));
        assert!(matches!(
            absent.remote_open_spec("x"),
            Err(NvimRemoteError::NotReady(_))
        ));
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn installed_nvim_listen_and_remote_open_integration() {
        if Command::new("nvim").arg("--version").output().is_err() {
            eprintln!("skipping Nvim integration test: nvim is not installed");
            return;
        }
        let root = temp("nvim-integration");
        fs::create_dir_all(&root).unwrap();
        let workspace = Workspace::discover(&root).unwrap();
        let profile = ManagedNvimProfile::materialize(temp("state")).unwrap();
        let generation = profile.generation(&workspace).unwrap();
        let mut command = Command::new(&generation.process_spec().program);
        command
            .args(&generation.process_spec().args)
            .arg("--headless")
            .current_dir(workspace.root());
        for (key, value) in &generation.process_spec().env {
            command.env(key, value);
        }
        let mut child = command.spawn().unwrap();
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(5);
        while !generation.endpoint().exists() && std::time::Instant::now() < deadline {
            std::thread::sleep(std::time::Duration::from_millis(20));
        }
        assert!(
            generation.endpoint().exists(),
            "Nvim listen socket was not ready"
        );
        let first = root.join("first file ü.txt");
        let second = root.join("second.rs");
        fs::write(&first, b"").unwrap();
        fs::write(&second, b"").unwrap();
        let controller = generation.controller(&workspace);
        controller.open_existing_file(&first).unwrap();
        controller.open_existing_file(&second).unwrap();
        controller.open_existing_file(&first).unwrap();

        let tabs = Command::new("nvim")
            .args([
                "--server",
                generation.endpoint().to_str().unwrap(),
                "--remote-expr",
                "tabpagenr('$')",
            ])
            .output()
            .unwrap();
        assert!(tabs.status.success());
        assert_eq!(String::from_utf8_lossy(&tabs.stdout).trim(), "2");
        let current = Command::new("nvim")
            .args([
                "--server",
                generation.endpoint().to_str().unwrap(),
                "--remote-expr",
                "expand('%:p')",
            ])
            .output()
            .unwrap();
        assert!(current.status.success());
        assert_eq!(
            Path::new(String::from_utf8_lossy(&current.stdout).trim()),
            first.canonicalize().unwrap()
        );
        let status = Command::new("nvim")
            .args([
                "--server",
                generation.endpoint().to_str().unwrap(),
                "--remote-send",
                "<Esc>:qa!<CR>",
            ])
            .status()
            .unwrap();
        assert!(status.success());
        let _ = child.wait();
        drop(generation);
        fs::remove_dir_all(root).unwrap();
    }
}
